// Code generated by "stringer -type=ActionType -trimprefix=Action"; DO NOT EDIT.

package game

import "strconv"

func _() {
	var x [1]struct{}
	_ = x[ActionUnknown-0]
	_ = x[ActionPass-1]
	_ = x[ActionBuild-2]
	_ = x[ActionDispatch-3]
}

const _ActionType_name = "UnknownPassBuildDispatch"

var _ActionType_index = [...]uint8{0, 7, 11, 16, 24}

func (i ActionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionType_index)-1 {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[idx]:_ActionType_index[idx+1]]
}
