// Code generated by "stringer -type=BuildingType -trimprefix=Building"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuildingUnknown-0]
	_ = x[BuildingForester-1]
	_ = x[BuildingMine-2]
	_ = x[BuildingBarracks-3]
	_ = x[BuildingFarm-4]
}

const _BuildingType_name = "UnknownForesterMineBarracksFarm"

var _BuildingType_index = [...]uint8{0, 7, 15, 19, 27, 31}

func (i BuildingType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BuildingType_index)-1 {
		return "BuildingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildingType_name[_BuildingType_index[idx]:_BuildingType_index[idx+1]]
}
