// Code generated by "stringer -type=ResourceType -trimprefix=Resource"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceUnknown-0]
	_ = x[ResourceWood-1]
	_ = x[ResourceStone-2]
	_ = x[ResourceCoal-3]
	_ = x[ResourceIron-4]
	_ = x[ResourceSteel-5]
	_ = x[ResourceGold-6]
	_ = x[ResourceFood-7]
}

const _ResourceType_name = "UnknownWoodStoneCoalIronSteelGoldFood"

var _ResourceType_index = [...]uint8{0, 7, 11, 16, 20, 24, 29, 33, 37}

func (i ResourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResourceType_index)-1 {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[idx]:_ResourceType_index[idx+1]]
}
