// Code generated by "stringer -type=TileType -trimprefix=Tile"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TileUnknown-0]
	_ = x[TileVoid-1]
	_ = x[TileWater-2]
	_ = x[TilePlains-3]
	_ = x[TileForest-4]
	_ = x[TileDesert-5]
	_ = x[TileJungle-6]
	_ = x[TileRock-7]
	_ = x[TileIron-8]
	_ = x[TileCoal-9]
	_ = x[TileGold-10]
}

const _TileType_name = "UnknownVoidWaterPlainsForestDesertJungleRockIronCoalGold"

var _TileType_index = [...]uint8{0, 7, 11, 16, 22, 28, 34, 40, 44, 48, 52, 56}

func (i TileType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TileType_index)-1 {
		return "TileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileType_name[_TileType_index[idx]:_TileType_index[idx+1]]
}
