// Code generated by "stringer -type=TroopType -trimprefix=Troop"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TroopUnknown-0]
	_ = x[TroopPeasant-1]
	_ = x[TroopArcher-2]
	_ = x[TroopKnight-3]
	_ = x[TroopScout-4]
}

const _TroopType_name = "UnknownPeasantArcherKnightScout"

var _TroopType_index = [...]uint8{0, 7, 14, 20, 26, 31}

func (i TroopType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TroopType_index)-1 {
		return "TroopType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TroopType_name[_TroopType_index[idx]:_TroopType_index[idx+1]]
}
