// Code generated by "stringer -type=UnitType -trimprefix=Unit unit.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitUnknown-0]
	_ = x[UnitPeasant-1]
	_ = x[UnitArcher-2]
	_ = x[UnitKnight-3]
	_ = x[UnitScout-4]
}

const _UnitType_name = "UnknownPeasantArcherKnightScout"

var _UnitType_index = [...]uint8{0, 7, 14, 20, 26, 31}

func (i UnitType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UnitType_index)-1 {
		return "UnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitType_name[_UnitType_index[idx]:_UnitType_index[idx+1]]
}
