// Code generated by "stringer -type=ConnectionState -trimprefix=Connection"; DO NOT EDIT.

package net

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionDisconnected-0]
	_ = x[ConnectionConnecting-1]
	_ = x[ConnectionConnected-2]
}

const _ConnectionState_name = "DisconnectedConnectingConnected"

var _ConnectionState_index = [...]uint8{0, 12, 22, 31}

func (i ConnectionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConnectionState_index)-1 {
		return "ConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionState_name[_ConnectionState_index[idx]:_ConnectionState_index[idx+1]]
}
