// Code generated by "stringer -type=UIState -trimprefix=State"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateDefault-0]
	_ = x[StateHover-1]
	_ = x[StateClick-2]
	_ = x[StateDisabled-3]
}

const _UIState_name = "DefaultHoverClickDisabled"

var _UIState_index = [...]uint8{0, 7, 12, 17, 25}

func (i UIState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UIState_index)-1 {
		return "UIState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UIState_name[_UIState_index[idx]:_UIState_index[idx+1]]
}
